"""adding width and heigh to LILA collected image

Revision ID: 0b46b94a11a0
Revises: 9e9b3518c577
Create Date: 2026-04-18 17:44:04.037350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b46b94a11a0'
down_revision: Union[str, Sequence[str], None] = '9e9b3518c577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lila_collected_images', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('lila_collected_images', sa.Column('height', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lila_collected_images', 'height')
    op.drop_column('lila_collected_images', 'width')
    # ### end Alembic commands ###
