"""inat context

Revision ID: 14501bf6590f
Revises: c345176b02e9
Create Date: 2026-04-25 01:34:18.491268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14501bf6590f'
down_revision: Union[str, Sequence[str], None] = 'c345176b02e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inat_capture_context',
    sa.Column('photo_uuid', sa.String(length=36), nullable=False),
    sa.Column('mean_r', sa.Float(), nullable=True),
    sa.Column('mean_g', sa.Float(), nullable=True),
    sa.Column('mean_b', sa.Float(), nullable=True),
    sa.Column('is_underwater', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['photo_uuid'], ['inat_filtered_observations.photo_uuid'], name=op.f('fk_inat_capture_context_photo_uuid_inat_filtered_observations')),
    sa.PrimaryKeyConstraint('photo_uuid', name=op.f('pk_inat_capture_context'))
    )
    op.create_index('ix_inat_capture_context_is_underwater', 'inat_capture_context', ['is_underwater'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inat_capture_context_is_underwater', table_name='inat_capture_context')
    op.drop_table('inat_capture_context')
    # ### end Alembic commands ###
