"""create inat tables

Revision ID: 5c29ee0d900c
Revises: 
Create Date: 2026-03-31 22:02:39.314020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c29ee0d900c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inat_taxa',
    sa.Column('taxon_id', sa.BigInteger(), nullable=False),
    sa.Column('ancestry', sa.String(), nullable=True),
    sa.Column('rank_level', sa.Float(), nullable=True),
    sa.Column('rank', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('taxon_id', name=op.f('pk_inat_taxa'))
    )
    op.create_index('ix_inat_ancestry_active', 'inat_taxa', ['ancestry', 'active'], unique=False)
    op.create_index('ix_inat_rank_level', 'inat_taxa', ['rank_level'], unique=False)
    op.create_table('inat_observations',
    sa.Column('observation_uuid', sa.String(length=36), nullable=False),
    sa.Column('observer_id', sa.BigInteger(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('positional_accuracy', sa.Integer(), nullable=True),
    sa.Column('taxon_id', sa.BigInteger(), nullable=True),
    sa.Column('quality_grade', sa.String(length=20), nullable=True),
    sa.Column('observed_on', sa.Date(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['taxon_id'], ['inat_taxa.taxon_id'], name=op.f('fk_inat_observations_taxon_id_inat_taxa')),
    sa.PrimaryKeyConstraint('observation_uuid', name=op.f('pk_inat_observations'))
    )
    op.create_index('ix_inat_taxa_id_quality', 'inat_observations', ['taxon_id', 'quality_grade'], unique=False)
    op.create_index('ix_nat_lat_long', 'inat_observations', ['latitude', 'longitude'], unique=False)
    op.create_index('ix_nat_observed_on', 'inat_observations', ['observed_on'], unique=False)
    op.create_table('inat_photos',
    sa.Column('photo_uuid', sa.String(length=36), nullable=False),
    sa.Column('photo_id', sa.BigInteger(), nullable=False),
    sa.Column('observation_uuid', sa.String(length=36), nullable=True),
    sa.Column('observer_id', sa.BigInteger(), nullable=True),
    sa.Column('extension', sa.String(length=10), nullable=True),
    sa.Column('license', sa.String(length=20), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['observation_uuid'], ['inat_observations.observation_uuid'], name=op.f('fk_inat_photos_observation_uuid_inat_observations')),
    sa.PrimaryKeyConstraint('photo_uuid', name=op.f('pk_inat_photos')),
    sa.UniqueConstraint('photo_id', name=op.f('uq_inat_photos_photo_id'))
    )
    op.create_index('ix_inat_photos_observation_uuid', 'inat_photos', ['observation_uuid'], unique=False)
    op.create_index('ix_inat_photos_photo_id', 'inat_photos', ['photo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inat_photos_photo_id', table_name='inat_photos')
    op.drop_index('ix_inat_photos_observation_uuid', table_name='inat_photos')
    op.drop_table('inat_photos')
    op.drop_index('ix_nat_observed_on', table_name='inat_observations')
    op.drop_index('ix_nat_lat_long', table_name='inat_observations')
    op.drop_index('ix_inat_taxa_id_quality', table_name='inat_observations')
    op.drop_table('inat_observations')
    op.drop_index('ix_inat_rank_level', table_name='inat_taxa')
    op.drop_index('ix_inat_ancestry_active', table_name='inat_taxa')
    op.drop_table('inat_taxa')
    # ### end Alembic commands ###
