"""LILA Yolo addition

Revision ID: 62a5c2a42bc2
Revises: 0b46b94a11a0
Create Date: 2026-04-18 20:43:08.099397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62a5c2a42bc2'
down_revision: Union[str, Sequence[str], None] = '0b46b94a11a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lila_yolo',
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('annotation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('file_name', name=op.f('pk_lila_yolo'))
    )
    op.create_index('ix_lila_yolo_file_name', 'lila_yolo', ['file_name'], unique=False)
    op.alter_column('lila_collected_images', 'width',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('lila_collected_images', 'height',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lila_collected_images', 'height',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('lila_collected_images', 'width',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_lila_yolo_file_name', table_name='lila_yolo')
    op.drop_table('lila_yolo')
    # ### end Alembic commands ###
