"""Changes to required tables and schema, drop view

Revision ID: 7c714d9c92ac
Revises: b03710e933e5
Create Date: 2026-04-12 22:25:40.957413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c714d9c92ac'
down_revision: Union[str, Sequence[str], None] = 'b03710e933e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inat_filtered_observations',
    sa.Column('photo_uuid', sa.String(length=36), nullable=False),
    sa.Column('photo_id', sa.BigInteger(), nullable=False),
    sa.Column('observation_uuid', sa.String(length=36), nullable=False),
    sa.Column('observer_id', sa.BigInteger(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('taxon_id', sa.BigInteger(), nullable=False),
    sa.Column('observed_on', sa.Date(), nullable=True),
    sa.Column('extension', sa.String(length=10), nullable=False),
    sa.Column('license', sa.String(length=20), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['taxon_id'], ['inat_taxa.taxon_id'], name=op.f('fk_inat_filtered_observations_taxon_id_inat_taxa')),
    sa.PrimaryKeyConstraint('photo_uuid', name=op.f('pk_inat_filtered_observations'))
    )
    op.create_index('ix_inat_filtered_observations_latitude_longitude', 'inat_filtered_observations', ['latitude', 'longitude'], unique=False)
    op.create_index('ix_inat_filtered_observations_observed_on', 'inat_filtered_observations', ['observed_on'], unique=False)
    op.create_index('ix_inat_filtered_observations_taxon_id', 'inat_filtered_observations', ['taxon_id'], unique=False)
    # Drop child table (inat_photos) before parent (inat_observations)
    # because inat_photos has FK → inat_observations.observation_uuid
    op.drop_index(op.f('ix_inat_photos_observation_uuid'), table_name='inat_photos')
    op.drop_index(op.f('ix_inat_photos_photo_id'), table_name='inat_photos')
    op.drop_table('inat_photos')
    op.drop_index(op.f('ix_inat_taxa_id_quality'), table_name='inat_observations')
    op.drop_index(op.f('ix_nat_lat_long'), table_name='inat_observations')
    op.drop_index(op.f('ix_nat_observed_on'), table_name='inat_observations')
    op.drop_table('inat_observations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inat_photos',
    sa.Column('photo_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('photo_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('observation_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('observer_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('extension', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('license', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['observation_uuid'], ['inat_observations.observation_uuid'], name=op.f('fk_inat_photos_observation_uuid_inat_observations')),
    sa.PrimaryKeyConstraint('photo_uuid', name=op.f('pk_inat_photos')),
    sa.UniqueConstraint('photo_id', name=op.f('uq_inat_photos_photo_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_inat_photos_photo_id'), 'inat_photos', ['photo_id'], unique=False)
    op.create_index(op.f('ix_inat_photos_observation_uuid'), 'inat_photos', ['observation_uuid'], unique=False)
    op.create_table('inat_observations',
    sa.Column('observation_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('observer_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('positional_accuracy', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('taxon_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('quality_grade', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('observed_on', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('anomaly_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['taxon_id'], ['inat_taxa.taxon_id'], name=op.f('fk_inat_observations_taxon_id_inat_taxa')),
    sa.PrimaryKeyConstraint('observation_uuid', name=op.f('pk_inat_observations'))
    )
    op.create_index(op.f('ix_nat_observed_on'), 'inat_observations', ['observed_on'], unique=False)
    op.create_index(op.f('ix_nat_lat_long'), 'inat_observations', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_inat_taxa_id_quality'), 'inat_observations', ['taxon_id', 'quality_grade'], unique=False)
    op.drop_index('ix_inat_filtered_observations_taxon_id', table_name='inat_filtered_observations')
    op.drop_index('ix_inat_filtered_observations_observed_on', table_name='inat_filtered_observations')
    op.drop_index('ix_inat_filtered_observations_latitude_longitude', table_name='inat_filtered_observations')
    op.drop_table('inat_filtered_observations')
    # ### end Alembic commands ###
