"""added proposed bbox to Inatclass

Revision ID: 972426b5c04c
Revises: ac79b76d2e0b
Create Date: 2026-05-17 17:44:56.694977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '972426b5c04c'
down_revision: Union[str, Sequence[str], None] = 'ac79b76d2e0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inat_classification_dataset', sa.Column('proposed_bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inat_classification_dataset', 'proposed_bbox')
    # ### end Alembic commands ###
