"""updated capture context

Revision ID: 998a3198ce78
Revises: 14501bf6590f
Create Date: 2026-05-03 15:08:48.092879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '998a3198ce78'
down_revision: Union[str, Sequence[str], None] = '14501bf6590f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inat_capture_context', sa.Column('stddev', sa.Float(), nullable=True))
    op.alter_column('inat_capture_context', 'is_underwater',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=True,
                postgresql_using='is_underwater::integer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inat_capture_context', 'is_underwater',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=True,
                postgresql_using='is_underwater::integer')
    op.drop_column('inat_capture_context', 'stddev')
    # ### end Alembic commands ###
