"""minor adjustment to index name

Revision ID: 9e9b3518c577
Revises: d17f111f414b
Create Date: 2026-04-15 18:06:50.411527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e9b3518c577'
down_revision: Union[str, Sequence[str], None] = 'd17f111f414b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inat_ancestry_active'), table_name='inat_taxa')
    op.drop_index(op.f('ix_inat_rank_level'), table_name='inat_taxa')
    op.create_index('ix_inat_taxa_ancestry_active', 'inat_taxa', ['ancestry', 'active'], unique=False)
    op.create_index('ix_inat_taxa_rank_level', 'inat_taxa', ['rank_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inat_taxa_rank_level', table_name='inat_taxa')
    op.drop_index('ix_inat_taxa_ancestry_active', table_name='inat_taxa')
    op.create_index(op.f('ix_inat_rank_level'), 'inat_taxa', ['rank_level'], unique=False)
    op.create_index(op.f('ix_inat_ancestry_active'), 'inat_taxa', ['ancestry', 'active'], unique=False)
    # ### end Alembic commands ###
