"""adding train split for Inat Classification

Revision ID: ac79b76d2e0b
Revises: c523988e75ac
Create Date: 2026-05-17 17:35:23.836875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac79b76d2e0b'
down_revision: Union[str, Sequence[str], None] = 'c523988e75ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inat_classification_dataset', sa.Column('train', sa.Integer(), nullable=True))
    op.create_index('ix_inat_classification_dataset', 'inat_classification_dataset', ['train'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inat_classification_dataset', table_name='inat_classification_dataset')
    op.drop_column('inat_classification_dataset', 'train')
    # ### end Alembic commands ###
