"""createa lila tables and success tracker

Revision ID: b03710e933e5
Revises: 5c29ee0d900c
Create Date: 2026-04-11 22:02:32.677855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b03710e933e5'
down_revision: Union[str, Sequence[str], None] = '5c29ee0d900c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lila_collected_images',
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('dataset', sa.String(length=255), nullable=False),
    sa.Column('is_train', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('file_name', name=op.f('pk_lila_collected_images'))
    )
    op.create_index('ix_lila_collected_images_dataset', 'lila_collected_images', ['dataset'], unique=False)
    op.create_index('ix_lila_collected_images_file_name', 'lila_collected_images', ['file_name'], unique=False)
    op.create_table('successful_uploads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_successful_uploads')),
    sa.UniqueConstraint('identifier', 'source', name='uq_identifier_source')
    )
    op.create_index('ix_successful_uploads_source', 'successful_uploads', ['source'], unique=False)
    op.create_table('lila_annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.String(length=255), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('w', sa.Float(), nullable=False),
    sa.Column('h', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['lila_collected_images.file_name'], name=op.f('fk_lila_annotations_image_id_lila_collected_images')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lila_annotations'))
    )
    op.create_index('ix_lila_annotations_category_id', 'lila_annotations', ['category_id'], unique=False)
    op.create_index('ix_lila_annotations_image_id', 'lila_annotations', ['image_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lila_annotations_image_id', table_name='lila_annotations')
    op.drop_index('ix_lila_annotations_category_id', table_name='lila_annotations')
    op.drop_table('lila_annotations')
    op.drop_index('ix_successful_uploads_source', table_name='successful_uploads')
    op.drop_table('successful_uploads')
    op.drop_index('ix_lila_collected_images_file_name', table_name='lila_collected_images')
    op.drop_index('ix_lila_collected_images_dataset', table_name='lila_collected_images')
    op.drop_table('lila_collected_images')
    # ### end Alembic commands ###
