"""Image quality tables

Revision ID: c345176b02e9
Revises: 62a5c2a42bc2
Create Date: 2026-04-24 18:22:41.888184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c345176b02e9'
down_revision: Union[str, Sequence[str], None] = '62a5c2a42bc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lila_image_quality',
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('uicm', sa.Float(), nullable=True),
    sa.Column('uism', sa.Float(), nullable=True),
    sa.Column('uiconm', sa.Float(), nullable=True),
    sa.Column('uiqm', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['file_name'], ['lila_collected_images.file_name'], name=op.f('fk_lila_image_quality_file_name_lila_collected_images')),
    sa.PrimaryKeyConstraint('file_name', name=op.f('pk_lila_image_quality'))
    )
    op.create_index('ix_lila_image_quality_uiqm', 'lila_image_quality', ['uiqm'], unique=False)
    op.create_table('inat_image_quality',
    sa.Column('photo_uuid', sa.String(length=36), nullable=False),
    sa.Column('uicm', sa.Float(), nullable=True),
    sa.Column('uism', sa.Float(), nullable=True),
    sa.Column('uiconm', sa.Float(), nullable=True),
    sa.Column('uiqm', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['photo_uuid'], ['inat_filtered_observations.photo_uuid'], name=op.f('fk_inat_image_quality_photo_uuid_inat_filtered_observations')),
    sa.PrimaryKeyConstraint('photo_uuid', name=op.f('pk_inat_image_quality'))
    )
    op.create_index('ix_inat_image_quality_uiqm', 'inat_image_quality', ['uiqm'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inat_image_quality_uiqm', table_name='inat_image_quality')
    op.drop_table('inat_image_quality')
    op.drop_index('ix_lila_image_quality_uiqm', table_name='lila_image_quality')
    op.drop_table('lila_image_quality')
    # ### end Alembic commands ###
